/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Martin' at '7.02.18 13:53' with Gradle 2.14.1
 *
 * @author Martin, @date 7.02.18 13:53
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
